# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 schedule:
 - cron: "0 7 * * *"
 
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: False
          SHOW_LOC_CHART: False
